apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chitchat
  namespace: argocd

spec:
  source:
    repoURl: https://github.com/Sarvesh-Work/chitchat-devops-cicd.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: chitchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
