apiVersion: v1
kind: Namespace
metadata:
  name: chitchat

# Note:
# The namespace is created manually during the initial cluster setup
# so that required secrets(i am not managing  secret using argo) can be applied in the correct namespace
# before running the CI/CD pipeline.
# this file is still kept in Git for GitOps state tracking.
