# this is a sample Secret manifest for the backend service
# actual secret values are NOT stored in the repository for security reasons.
# secrets are applied manually to the Kubernetes cluster to prevent sensitive data leakage
# replace the placeholder values with real secrets before applying in your environment.
apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: chitchat
  labels:
    app: backend

type: Opaque

data:
  MONGODB_URL: "Your db url"
  JWT_KEY: "Your jwt key"
  CLOUDINARY_API_KEY: "Your cloudinary api key"
  CLOUDINARY_API_SECRET: "Your cloudinary api secret"
