apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: chitchat
  name: backend-deployment-chitchat
  labels:
    app: chitchat-backend

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - image: sarvesh9075/chitchat-chat-app-backend:v1.0.0-c16e86f
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8080

          envFrom:              
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
                
# secret is created manually in the cluster using kubectl.
# This is done intentionally to avoid committing secret YAML files to GitHub.
# The deployment references the existing secret using secretRef.

